training_pipeline_config:
 pipeline: US_Visa
 artifact_dir: artifact

data_ingestion_config:
 dataset_download_url: url
 raw_data_dir: raw_data
 ingested_dir: ingested_data
 ingested_train_dir: train
 ingested_test_dir: test


data_validation_config:
schema_dir: config
schema_file_dir: schema.yaml


data_transformation_config:


model_training_config:


model_evaluation_config:


model_pusher_config:
